### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by hjhyhg** [True-cc/BuilderHelper#5]
---- Minecraft Crash Report ----
// You're mean.

Time: 5/21/21 5:43 PM
Description: Unexpected error

java.lang.NoSuchMethodError: io.github.coolmineman.bitsandchisels.api.client.RedBoxCallback$IRedBoxDrawer.drawRedBox(Lnet/minecraft/class_4587;Lnet/minecraft/class_4588;Lnet/minecraft/class_2338;IIIDDD)V
	at uwu.smsgamer.builderhelper.compat.chitsAndBisels.items.BigBitItem.lambda$initClient$2(BigBitItem.java:98)
	at uwu.smsgamer.builderhelper.compat.chitsAndBisels.items.BigBitItem$$Lambda$2597/1618977160.drawBoxes(Unknown Source)
	at io.github.coolmineman.bitsandchisels.api.client.RedBoxCallback.lambda$static$0(RedBoxCallback.java:14)
	at io.github.coolmineman.bitsandchisels.api.client.RedBoxCallback$$Lambda$2591/999014315.drawBoxes(Unknown Source)
	at net.minecraft.class_761.handler$zfn000$drawBlockOutlineAddon(class_761.java:3110)
	at net.minecraft.class_761.method_22712(class_761.java)
	at net.minecraft.class_761.method_22710(class_761.java:1333)
	at net.minecraft.class_757.method_3188(class_757.java:727)
	at net.minecraft.class_757.redirect$zkp000$redirectRenderingWorld(class_757.java:3552)
	at net.minecraft.class_757.method_3192(class_757.java:546)
	at net.minecraft.class_310.method_1523(class_310.java:1048)
	at net.minecraft.class_310.method_1514(class_310.java:681)
	at net.minecraft.client.main.Main.main(Main.java:215)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:226)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:146)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at uwu.smsgamer.builderhelper.compat.chitsAndBisels.items.BigBitItem.lambda$initClient$2(BigBitItem.java:98)
	at uwu.smsgamer.builderhelper.compat.chitsAndBisels.items.BigBitItem$$Lambda$2597/1618977160.drawBoxes(Unknown Source)
	at io.github.coolmineman.bitsandchisels.api.client.RedBoxCallback.lambda$static$0(RedBoxCallback.java:14)
	at io.github.coolmineman.bitsandchisels.api.client.RedBoxCallback$$Lambda$2591/999014315.drawBoxes(Unknown Source)
	at net.minecraft.class_761.handler$zfn000$drawBlockOutlineAddon(class_761.java:3110)
	at net.minecraft.class_761.method_22712(class_761.java)
	at net.minecraft.class_761.method_22710(class_761.java:1333)
	at net.minecraft.class_757.method_3188(class_757.java:727)
	at net.minecraft.class_757.redirect$zkp000$redirectRenderingWorld(class_757.java:3552)

-- Affected level --
Details:
	All players: 1 total; [class_746['gamebird123'/254, l='ClientWorld minecraft:overworld', x=-593.97, y=114.00, z=40.88]]
	Chunk stats: Client Chunks (ImmPtl) 254
	Level dimension: minecraft:overworld
	Level spawn location: World: (-519,69,85), Chunk: (at 9,4,5 in -33,5; contains blocks -528,0,80 to -513,255,95), Region: (-2,0; contains chunks -64,0 to -33,31, blocks -1024,0,0 to -513,255,511)
	Level time: 408705 game time, 408705 day time
	Server brand: fabric
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:449)
	at net.minecraft.class_310.method_1587(class_310.java:2239)
	at net.minecraft.class_310.method_1514(class_310.java:704)
	at net.minecraft.client.main.Main.main(Main.java:215)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:226)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:146)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)

-- System Details --
Details:
	Minecraft Version: 1.16.5
	Minecraft Version ID: 1.16.5
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1051405232 bytes (1002 MB) / 2080374784 bytes (1984 MB) up to 2147483648 bytes (2048 MB)
	CPUs: 8
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		bitsandchisels: BitsAndChisels 2.3.0
		builder_helper: BuilderHelper 0.1
		cloth-basic-math: Cloth Basic Math 0.5.1
		cloth-config2: Cloth Config v4 4.11.15
		fabric: Fabric API 0.33.0+1.16
		fabric-api-base: Fabric API Base 0.2.1+9354966b7d
		fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.0.0+dc716ea17d
		fabric-biome-api-v1: Fabric Biome API (v1) 3.1.1+ca58154a7d
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.5+ca58154a7d
		fabric-command-api-v1: Fabric Command API (v1) 1.1.1+351679a77d
		fabric-commands-v0: Fabric Commands (v0) 0.2.2+ca58154a7d
		fabric-containers-v0: Fabric Containers (v0) 0.1.11+9354966b7d
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.2.1+ca58154a7d
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.3+ca58154a7d
		fabric-dimensions-v1: fabric-dimensions-v1 2.0.6+9354966b7d
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.0.3+ca58154a7d
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.2+ca58154a7d
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.1+ca58154a7d
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.6+ca58154a7d
		fabric-item-api-v1: Fabric Item API (v1) 1.2.1+ca58154a7d
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.7+2868a2287d
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.4+9354966b7d
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.1+ca58154a7d
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.2.1+ca58154a7d
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.2+ca58154a7d
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.3+ca58154a7d
		fabric-models-v0: Fabric Models (v0) 0.3.0+bc7a746f7d
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.1+ca58154a7d
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.8+ca58154a7d
		fabric-networking-v0: Fabric Networking (v0) 0.3.2+ca58154a7d
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.9.4+9354966b7d
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.2+ca58154a7d
		fabric-particles-v1: Fabric Particles (v1) 0.2.4+ca58154a7d
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.7.4+ca58154a7d
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.2+2868a2287d
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.4+ca58154a7d
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 2.3.0+2868a2287d
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.5+ca58154a7d
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.13+ca58154a7d
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.2+ca58154a7d
		fabric-rendering-v1: Fabric Rendering (v1) 1.6.0+2868a2287d
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.6+2868a2287d
		fabric-screen-api-v1: Fabric Screen API (v1) 1.0.0+c045166c7d
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.5+9354966b7d
		fabric-structure-api-v1: Fabric Structure API (v1) 1.1.4+ca58154a7d
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.1.1+ca58154a7d
		fabric-textures-v0: Fabric Textures (v0) 1.0.6+ca58154a7d
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.6+ca58154a7d
		fabricloader: Fabric Loader 0.11.3
		imm_ptl_core: Immersive Portals Core 0.90
		immersive_portals: Immersive Portals 0.90
		java: Java HotSpot(TM) 64-Bit Server VM 8
		leadvillagers: Lead Villagers 2.1.0+mc1.16.1
		minecraft: Minecraft 1.16.5
		modmenu: Mod Menu v1.16.8+unknown.bd9230a
		pehkui: Pehkui 2.1.0+21w18a
		stacc: Stacc 1.0.1
		worldedit: WorldEdit 7.2.5+57d5ac9
		xaerominimap: Xaero's Minimap 21.8.1
		xaeroworldmap: Xaero's World Map 1.13.5
		xlpackets: XLPackets 1.1
	Launched Version: fabric-loader-0.11.3-1.16.5
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: Intel(R) UHD Graphics GL version 4.6.0 - Build 27.20.100.8476, Intel
	GL Caps: Using framebuffer using OpenGL 3.0
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Graphics mode: fast
	Resource Packs: vanilla, Fabric Mods, file/1.17.zip (incompatible), file/faithful-64-1.17.zip (incompatible)
	Current Language: English (US)
	CPU: 8x Intel(R) Core(TM) i5-10300H CPU @ 2.50GHz

**Comment by SelfMadeSystem** [comment]
ah... that's... that's just brilliant. Honestly, I don't do much in Minecraft anymore but I suppose I could fix this.
